name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - name: foo
      shell: bash
      run: |
        echo `which rustup`
        echo `which rustc`
        rustup self uninstall -y || echo "uninstall not necessary"
        rustc -V || echo "failed"
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain beta --profile=minimal
        echo "##[add-path]$HOME/.cargo/bin"
        export PATH=$HOME/.cargo/bin:$PATH
        echo `which rustup`
        echo `which rustc`
        rustc -V
    - name: bar
      shell: bash
      run: |
        echo `which rustup`
        echo `which rustc`
        rustc -V        
        env
