name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: macos-latest    
    steps:
    - name: foo
      shell: bash
      run: |
        echo `which rustup`
        echo `which rustc`
        rustup self uninstall -y || echo "uninstall not necessary"
        rustc -V || echo "failed"
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain beta --profile=minimal
        echo "##vso[task.prependpath]$HOME/.cargo/bin"
        echo `which rustup`
        echo `which rustc`
        rustc -V
    - name: bar
      shell: bash
      run: |
        echo `which rustup`
        echo `which rustc`
        rustc -V        
        env
